### ISSUE TITLE
UnboundLocalError

### ISSUE THREAD

**Issue by Lixia1221** [ZiweiWangTHU/BiDet#24]
(base) fsr@3090:~/BiDet-master$ python ssd/train_bidet_ssd.py --dataset='VOC/COCO' --data_root='path/to/dataset' --basenet='path/to/pretrain_backbone'
Traceback (most recent call last):
  File "ssd/train_bidet_ssd.py", line 414, in <module>
    train()
  File "ssd/train_bidet_ssd.py", line 123, in train
    ssd_net = build_bidet_ssd('train', cfg['min_dim'], cfg['num_classes'],
UnboundLocalError: local variable 'cfg' referenced before assignment
如何解决？

**Comment by Wuziyi616** [comment]
Please refer to [these lines of code](https://github.com/ZiweiWangTHU/BiDet/blob/master/ssd/train_bidet_ssd.py#L105-L112). You can see that we assign the variable of cfg according to your specified dataset. If you want to train PASCAL VOC, just use ```python ssd/train_bidet_ssd.py --dataset=VOC``` and specify the data_root as well as pretrained backbone weight.
