### ISSUE TITLE
Could you provide a trained SSD model with Bi-det strategy?

### ISSUE THREAD

**Issue by puhan123** [ZiweiWangTHU/BiDet#25]
Hello! Could you provide a trained SSD model with Bi-det strategy? I need to use it for comparative analysis.

 Although I use the tricks proposed in existed issues, NaN is always present during training.

Thank you very much!

**Comment by Wuziyi616** [comment]
Hi @puhan123, really sorry to hear that. Yes I am trying to re-train my model. However, since I am no longer in that lab, I can't get access to the original trained weight. A re-training is on the way. I will try to reply to you in next week.

**Comment by puhan123** [comment]
Thank you very much !

**Comment by Wuziyi616** [comment]
Hi! The pre-trained weight of BiDet SSD300 on Pascal VOC has been uploaded [here](https://drive.google.com/file/d/1mURBX-EtoFanp-8wP6-n3u0E6Mq3enkv/view). Have a try!

Feel free to re-open this issue should you have any questions :)

**Comment by puhan123** [comment]
Thank you very much! You are so nice!
