### ISSUE TITLE
The test result of COCO by using faster-rcnn

### ISSUE THREAD

**Issue by TIEHua** [ZiweiWangTHU/BiDet#27]
Sorry to bother you. I use faster-rcnn to test COCO. The mAP is 12.7%, which is lower than the result in the paper (15.7%);
The parameters I used are the default parameters in the trainval_net.py. How many epochs do you choose for training? Thanks for your time. I am waiting for your reply.

**Comment by Wuziyi616** [comment]
Sorry I can't remember that clearly. If you follow the number in our paper/code and didn't succeed, I suppose you should tune it yourself, e.g. decay the lr when test performance didn't improve during last 2 epochs. If you don't mind, I will try to re-train a BiDet FRCNN on COCO, but it may take a while because I am busy during weekdays. Let me know if you need the pre-trained weight.

**Comment by TIEHua** [comment]
Thanks for you reply. I will tune it myself. And if you have time to re-train the FRCNN on COCO, I will wait for the pre-trained weight.

**Comment by Wuziyi616** [comment]
I will suggest you train with larger batch size. When I trained with 32 or 64, I often got better AP and more stable results. The re-training is undergoing.

**Comment by TIEHua** [comment]
Thank you. I will try to enlarge the batch size

**Comment by Wuziyi616** [comment]
Hi @TIEHua, sorry for the late reply. I recently trained a **Bi-Real** Faster R-CNN with ResNet-18 backbone and got 14.4 mAP as reported in the paper. You can download the weight [here](https://drive.google.com/file/d/1gjtIg_oBTXm0s1ql-IyXUp5FlxXbBZsU/view?usp=sharing). The BiDet version requires larger batch size which I currently don't have access to (I will join another lab as a PhD this fall, so now I have no GPU server in any labs...). I will appreciate it a lot if you can be patient and wail till then.

**Comment by TIEHua** [comment]
Thank you very much. Could you please tell me the parameters you use and how many epochs do you use for training the model?

**Comment by Wuziyi616** [comment]
Hi, I use 32 batch size with 2 GPUs and Adam optimizer. Train 15 epochs with lr=1e-2, then decay by 0,1 at epoch16, train 5 epochs with lr=1e-3, then decay by 0.1 at epoch21, and finally train 2 epochs with lr=1e-4.

- epoch 1~15, lr=1e-2
- epoch 16~20, lr=1e-3
- epoch 21~22, lr=1e-4

Hope that helps you.

**Comment by TIEHua** [comment]
Thank you very much.

**Comment by AmingWu** [comment]
@TIEHua ，How to get the dataset of Minval50K？When I run the code, there is an error.

FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Desktop/wam/BiDet/data/annotations/instances_valminusminival2014.json'

Could you give me some advice?

**Comment by TIEHua** [comment]
> @TIEHua ，How to get the dataset of Minval50K？When I run the code, there is an error.
> 
> FileNotFoundError: [Errno 2] No such file or directory: '/home/user/Desktop/wam/BiDet/data/annotations/instances_valminusminival2014.json'
> 
> Could you give me some advice?

Yeah , you need download this file from COCO dataset.
