### ISSUE TITLE
Training Time

### ISSUE THREAD

**Issue by AmingWu** [ZiweiWangTHU/BiDet#32]
Dear authors,

How long does your model need to train?

**Comment by Wuziyi616** [comment]
Well it depends. If I remember correctly, training BiDet-SSD on VOC takes less than 1 day, while on COCO it needs 2-3 days to converge. Faster R-CNN uses less time I think (about half the time needed for SSD).

**Comment by kj-kx** [comment]
hi,could you tell me the computer configuration？
