### ISSUE TITLE
测试错误

### ISSUE THREAD

**Issue by AmingWu** [ZiweiWangTHU/BiDet#33]
你好，我现在已经成功训练训练了模型，但是测试时出现了错误：Network is not defined. 我的训练命令是

python faster_rcnn/trainval_net.py --dataset='coco' --data_root='/home/user/Desktop/wam/BiDet/data' --basenet='/home/user/Desktop/wam/BiDet/faster_rcnn/pretrain/resnet18.pth'

测试命令是：

python test_net.py --dataset='coco' --checkpoint='./logs/coco/bidet18_IB/2021-07-06 20:46:25/model_50_loss_0.771_lr_1.0000000000000002e-06_rpn_cls_0.1611_rpn_bbox_0.0987_rcnn_cls_0.3137_rcnn_bbox_0.197_rpn_prior_0.0_rpn_reg_0.0005_head_prior_0.0_head_reg_0.0.pth'

您能给我一些建议吗，谢谢您。

![QQ截图20210712125941](https://user-images.githubusercontent.com/38445175/125233403-0acba700-e311-11eb-81bc-70208b1f09e5.jpg)

**Comment by Wuziyi616** [comment]
需要加上额外的参数 `--backbone=bireal18`
