### ISSUE TITLE
python setup.py build develop报错

### ISSUE THREAD

**Issue by kj-kx** [ZiweiWangTHU/BiDet#34]
您好，我在编译setup.py时，遇到了error: torch/extension.h: No such file or directory这个错误？我想请教您这个问题要如何解决

**Comment by crjxixixi** [comment]
I meet the same question, could you tell how can I solve it?

**Comment by kj-kx** [comment]
you can see this web：https://github.com/facebookresearch/maskrcnn-benchmark/issues/1242
