### ISSUE TITLE
训练ssd模型时，调整学习率函数参数错误

### ISSUE THREAD

**Issue by kj-kx** [ZiweiWangTHU/BiDet#36]
您好，我在复现您的ssd模型在voc数据集上，遇到了这个错误，adjust_learning_rate(optimizer, args.gamma, step_index)
TypeError: adjust_learning_rate() takes 2 positional arguments but 3 were given
看您定义的def adjust_learning_rate(optimizer, new_lr)只需要两个函数。
是我哪里没弄明白吗？

**Comment by Wuziyi616** [comment]
这确实是一个问题，我会马上修复一下。应该是计算好 decay 后的结果再输入 
```
new_lr = get_lr(optimizer) * args.gamma
adjust_learning_rate(optimizer, new_lr)
```

**Comment by kj-kx** [comment]
谢谢你这么及时的回复，多谢您的指点

**Comment by kj-kx** [comment]
您好，训练到60000个迭代的时候，每一百个迭代比最开始迭代的速度差不多要花四到五倍的时间，您训练的时候有遇到这种现象吗？

**Comment by Wuziyi616** [comment]
你好，这是正常的，因为从第一次 decay lr (60000 iter) 开始我们会计算 BiDet 特有的 loss，这里涉及到 for 循环，非常的慢

**Comment by kj-kx** [comment]
我还想问一下，这个程序是不是训练时cpu用的很多，您当时的电脑配置是怎么样的？

**Comment by Wuziyi616** [comment]
是的，我当时是 2x RTX 2080Ti GPU, 32 核 CPU 内存大概 256G

**Comment by kj-kx** [comment]
要是我想回到一个最简单的二进制检测网络，这个代码要怎么修改？

**Comment by Wuziyi616** [comment]
那就不计算 BiDet loss 就行了，[这边](https://github.com/ZiweiWangTHU/BiDet/blob/fc54511195201aa0e9c4b599fd86a07ad80f342f/ssd/train_bidet_ssd.py#L197)的两项全都设成 0 吧

**Comment by kj-kx** [comment]
我又遇到一个问题，当我训练自己的数据集时，损失停留在11左右，几乎无法下降，这要怎么处理？

**Comment by Wuziyi616** [comment]
你好，我建议是先拿非二值化的 SSD 在你自己的数据集上训练，已验证你的数据处理、标签标注是否有问题。没有更多的信息我也不可能说怎么处理

**Comment by kj-kx** [comment]
您在代码实现中好像没有用到bi-real的改进梯度误差这一点？
class SignSTE(Function):
    @staticmethod
    def forward(ctx, input):
        ctx.save_for_backward(input)
        input = input.sign()
        return input

    @staticmethod
    def backward(ctx, grad_output):
        input, = ctx.saved_tensors
        mask = input.ge(-1) & input.le(1)
        grad_input = torch.where(mask, grad_output, torch.zeros_like(grad_output))
        return grad_input
直接用的直通器？

**Comment by kj-kx** [comment]
我看错了，
class SignTwoOrders(Function):
    @staticmethod
    def forward(ctx, input):
        ctx.save_for_backward(input)
        input = input.sign()
        return input

    @staticmethod
    def backward(ctx, grad_output):
        input, = ctx.saved_tensors

        grad_input_wrt_output2 = torch.zeros_like(grad_output)
        ge0_lt1_mask = input.ge(0) & input.lt(1)
        grad_input_wrt_output2 = torch.where(ge0_lt1_mask, (2 - 2 * input), grad_input_wrt_output2)
        gen1_lt0_mask = input.ge(-1) & input.lt(0)
        grad_input_wrt_output2 = torch.where(gen1_lt0_mask, (2 + 2 * input), grad_input_wrt_output2)
        grad_input = grad_input_wrt_output2 * grad_output

        return grad_input
这里实现了，所以是可以选择运用bireal的梯度误差估计方法和原始的STE吗？

**Comment by Wuziyi616** [comment]
是的，我们的代码应该是有正确实现 BiReal 的方法的
