### ISSUE TITLE
Where can I find the BiDet-SC model in the code base for COCO? 

### ISSUE THREAD

**Issue by uzair789** [ZiweiWangTHU/BiDet#38]
Hi, I am working on recreating your results but I cant seem to find the model setting for Bidet-sc which you have reported in the paper. Can you please point me to the file where I can see the skip connections you have built in Bidet-SC version of Bidet? THank you.

**Comment by Wuziyi616** [comment]
Oh, actually the code we provided is BiDet-SC. In our paper, BiDet refers to using XNOR-Net binarization strategy, while BiDet-SC means using Bi-Real-Net binarization. You can see that all the binary Conv layer we use are Bi-Real style, and we add additional shortcuts for VGG and ResNet
