### ISSUE TITLE
Deploy in Xilinx FPGA

### ISSUE THREAD

**Issue by samagalhaes** [ZiweiWangTHU/BiDet#39]
Dear,

I am trying to deploy these models for Xilinx FPGA using the FINN framework. Do you have in your knowledge any incompatibility? Currently, I am having many issues while converting to the ONNX format. 

Thanks

**Comment by Wuziyi616** [comment]
I am sorry but we don't have knowledge in ONNX export or FPGA deployment :( Maybe you can have a look at this framework [daBNN](https://github.com/JDAI-CV/dabnn)? I saw an Bi-Real-Net ResNet deployment example there.

**Comment by samagalhaes** [comment]
Thank you for the quick answer. Unfortunately, daBNN doesn't look to export to HLS or another FPGA compatible format.
