### ISSUE TITLE
About xnor-bitcount implementation

### ISSUE THREAD

**Issue by ztianlin** [ZiweiWangTHU/BiDet#4]
Hi, really appreciated for your excellent work.

Like many other open-source binary quantization repositories, I notice that you conduct **_BinarizeConv2d_** based on **_torch.nn.functional.conv2d_**. For training everything is good.  But for inference, it seems that the absence of xnor-bitcount based convolution keeps this excellent work from extreme superiority. 

Have you implemented this or have you intended to do so? Thanks very much.

**Comment by Wuziyi616** [comment]
Hi! Thank you for your interest on our work. Actually our work doesn't focus on implementing 'real' binary neural networks on hardwares, we just propose a better way to train it.
For the implementation of binary operations like xnor and bitcount, I recommend you to [this](https://github.com/JDAI-CV/dabnn) repo which has inference time tested for binary neural networks on mobile devices.

**Comment by ztianlin** [comment]
Great! Thanks again ^_^
