### ISSUE TITLE
test error

### ISSUE THREAD

**Issue by never-to-never** [ZiweiWangTHU/BiDet#42]
Hello, I encountered an error when executing the test command after the training was completed. The error message was: PermissionError: [Errno 13] Permission denied:'/path'. Can you give a solution? thank you very much!

**Comment by Wuziyi616** [comment]
More detailed information about the error is needed (e.g. which file which line did this error occur). I think it's because you forget the change some path variables, and they are initially set as `/path/xxx` which is definitely wrong
