### ISSUE TITLE
params

### ISSUE THREAD

**Issue by kj-kx** [ZiweiWangTHU/BiDet#43]
您好，我在学习您的工作，我有一个疑问。
我在用thop计算ssd300的params与MFLOPs时，浮点运算数大致一样，但是params为26.28M，而不是文中所说的100.28M？？？

**Comment by Wuziyi616** [comment]
你好，这个数字是从前人工作中摘录的，应该是一个公认的参数量，可能你的计算代码有误？我记得我算出来也是差不多这个数

**Comment by puhan123** [comment]
请问您计算二值目标检测器的FLOPs时，把乘法和加法都算进去了吗？ @Wuziyi616 

另外，您有计算过BiDet算法的fps吗？非常感谢~

**Comment by Wuziyi616** [comment]
你好，FPS 涉及到具体实现 e.g. 使用二值化框架重写模型并部署到特定设备上，这部分内容超出了本文的研究范围，因此没有实现

对于 BiDet FLOPs 的计算，我是将模型的所有二值化模块 FLOPs 取出，除以 64 (见 BirealNet 的解释)，加上所有实值化模块 FLOPs 得到的
