### ISSUE TITLE
Vgg arch in SSD implementation is different from original vgg

### ISSUE THREAD

**Issue by uzair789** [ZiweiWangTHU/BiDet#44]
Hi Guys, thank you for the awsome implementation. I had a question about the bidet_vgg in the ssd implementation. Your bidet_vgg has got extra layers and you have replaced all the maxpool layers with Conv layers with downsample. Why did you guys make these changes? Is the original vgg architecture too low in complexity to learn if you binarize it?

**Comment by Wuziyi616** [comment]
Hi, thanks for your interest in our work. Your understanding is correct. We discovered that, pooling layers in BNN hurts the performance significantly, especially in the detection task. So we have to replace them with Conv layers.

**Comment by uzair789** [comment]
I see, thank you for the reply.
