### ISSUE TITLE
有关于模型在coco数据集上的表现

### ISSUE THREAD

**Issue by tongchangD** [ZiweiWangTHU/BiDet#46]
博士，您好
看您的介绍像是国人，如此我就直接用中文表达我的疑惑了，望请解答。   

请问BiDet中涉及到的模型在coco数据上能否达到yolov3在coco数据集上的效果，即输入相近的Map值。  

例如在coco数据上达到30左右的Map值。   

我看您在此仓的部分issue中有提到一个基于Resnet18的模型，其Map值为14.4，且论文中展示的在coco数据集上的Map为15.7，请问这些值是此仓的模型的最理想值吗，能否有提升的空间，即还能否高    

祝好

**Comment by Wuziyi616** [comment]
你好 经过我们很努力的尝试 可以稍微提高 但离 30 还是差得很远，因为我们是二值网络 注重于降低计算量和显存，因为性能方面会有一定受损
您或许可以关注一下最近的工作 比如[这篇](https://openaccess.thecvf.com/content/CVPR2021/papers/Xu_Layer-Wise_Searching_for_1-Bit_Detectors_CVPR_2021_paper.pdf)，根据他们的 Table 3, 在 COCO 上达到了 30 左右的性能

**Comment by tongchangD** [comment]
好的。非常感谢博士您的回复。  
我现在就是想找一个二值网络，我的目标也是想找一个降低计算量和显存的网络，看在 COCO 上能否达到30左右（或较近）的Map。您说的这篇论文，我会仔细去阅读，遗憾的是他未公开源码，而我的复现能力菜的抠脚，也不知道能否复现。  
  
祝好

**Comment by tongchangD** [comment]
博士，您好  
我还有一个疑问， 您设计的这个全部都是二值计算，还是除了第一层和最后一层是全精度的，其他都是二值计算  
祝好

**Comment by Wuziyi616** [comment]
你好 依照二值网络的惯例 第一和最后一层是全精度 只有中间是二值
很好理解 因为输出层要预测 bbox coordinate, 这是一个连续的值，因此如果仍然用二值输出层 只能得到整数预测，误差必然很大

**Comment by tongchangD** [comment]
是的，我之前尝试过将其他网络改成这样（第一和最后一层是全精度，中间层为二值），但与全精度计算的结果相差就比较大，然后搜索资料时发现您的论文与代码，感觉还比较OK，然后就开始训练测试。可惜的是我还没复现到您论文的效果，您当时训练花了多久，然后用的啥平台呀。

**Comment by Wuziyi616** [comment]
年代过于久远... 应该就是正常 2张 (?) GTX1080Ti 训要训几天 具体不记得了 大概 3 天？

**Comment by tongchangD** [comment]
请问是8G显存吗？

**Comment by tongchangD** [comment]
不是，查了一下，是12G显存。是说我的8G小卡训练起来batchsize设置为8，num_worker=1时，训练起来都为何这么吃力呢   

祝好
