### ISSUE TITLE
关于计算量和参数量

### ISSUE THREAD

**Issue by yuhua666** [ZiweiWangTHU/BiDet#47]
我有注意到您提及通过thop库来计算参数量和计算量。
我的理解是，这个库上没有实现自定义模块的计算方式，您二值化后的模块是如何计算的呢，这部分的代码有开源吗？很期待能够学习。

**Comment by Wuziyi616** [comment]
你好，在[这里](https://github.com/Lyken17/pytorch-OpCounter#how-to-use)有提及自定义模块的实现方式，见 `Define the rule for 3rd party module` 部分。简而言之，二值操作的 params 通常是全精度操作的 1/32, FLOPS 也是类似的比例关系

**Comment by tongchangD** [comment]
> 我有注意到您提及通过thop库来计算参数量和计算量。 我的理解是，这个库上没有实现自定义模块的计算方式，您二值化后的模块是如何计算的呢，这部分的代码有开源吗？很期待能够学习。

哈哈哈，刚刚想提问问这个来着，没想到你提前问了参数量和计算量的问题
