### ISSUE TITLE
关于训练

### ISSUE THREAD

**Issue by tongchangD** [ZiweiWangTHU/BiDet#48]
昨儿尝试在coco2017上训练SSD300的二值网络，今早发现loss呈现这种趋势，您觉得是不是该cancel重新开训了。   

![image](https://user-images.githubusercontent.com/36293393/203192681-e2ace5d2-9d4e-485b-81be-4cf206b6e354.png)

请问40K时的一波更新学习率lr咋会引起这么大的反应？

**Comment by tongchangD** [comment]
不对，这里的变化是加入其他的loss(`reg_loss`和`prior_loss`),而且我的`reg_loss`和`prior_loss`保存错误，都是保存的`conf_loss`值

**Comment by Wuziyi616** [comment]
因为不确定是代码问题 还是 Python package 问题，能否现在 PASCAL VOC 试试复现结果？不过确实 二值网络的训练非常不稳定，可以参考[这个](https://github.com/ZiweiWangTHU/BiDet#frequently-asked-questions)的最后一条，在一个 issue 里讨论了很多观察。不过我没遇到过 decay lr 反而 loss 上升这么多的情况..
