### ISSUE TITLE
关于二值化带来的参数缩减

### ISSUE THREAD

**Issue by yuhua666** [ZiweiWangTHU/BiDet#49]
关于参数缩减，相比vgg、resnet-18，mobilenet的二值化减少的参数量很少，这是什么原因导致的呢？

**Comment by Wuziyi616** [comment]
如[这里](https://github.com/ZiweiWangTHU/BiDet/issues/46#issuecomment-1320815083)所述，我们没有二值化第一层和最后一层 (即 detection head)，所以 detector 轻量化的大多为 backbone
VGG, ResNet 本身参数量/计算量不小，所以可以降低不少；但 MobileNet backbone 本身就很轻量 参数和计算量都很少，减少有限

**Comment by yuhua666** [comment]
所以faster rcnn、SSD的除了backbone的其他部分binary带来的减少量也很有限吗？除backbone的部分因binary减少了多少呢，如果没有精确的量，能告知我大致的概念吗，这是我目前比较迷惑的地方。希望您可以帮助我，十分感谢！

**Comment by Wuziyi616** [comment]
大概就是 1/32 因为 float32 --> 1bit (binary), 考虑第一层因为 image 没有经过 downsample 还比较大，所以我估计降低量在 10-20x 左右吧；具体的数字已经不记得了.. 计算的代码也早就丢了 (笑)

**Comment by yuhua666** [comment]
比较好奇的是比例？主要是backbone降的多吗，backbone和除backbone的其他部分相比，哪部分参数量降的多呢，降低的部分大致是几比几？
