### ISSUE TITLE
Is the backbone network binarized?

### ISSUE THREAD

**Issue by hukim93** [ZiweiWangTHU/BiDet#5]
Hi, I really appreciate your valuable work.

I just wonder which part of the SSD network is binarized.
In your paper, SSD model consists of a backbone network and a detection network.
Are both parts are binarized?
If not, which layers have to be kept with full precision?

**Comment by Wuziyi616** [comment]
Hi, thank you for your attention! Both the backbone and detection heads are binarized except three layers. They are the first layer of the backbone, the last layer of the backbone and the last layer of the detection network.

The reason for keeping the first two layers full-precision is for accuracy, also it's a common practice in BNN setting. The reason for keeping the third layer full-precision is that we need to output float values for localization and classification. So I think these are necessary.

**Comment by hukim93** [comment]
Thanks a lot!
Can I ask you more details about the 'last layer of the detection network'?
Typically, every intermediate feature map in the detection network are connected to an individual classifier for multi-box detection.
Are all of these classifiers are kept with full precision? Or only the classifier connected to the last intermediate feature map of the detection network is full precision?

**Comment by Wuziyi616** [comment]
Thank you for your question. You are right there are multi-scale classifiers in SSD's detection network, and we want all of them to have float output, so we keep all the output layers full-precision. And that's why the decrease of parameter size of SSD is much less than Faster R-CNN, which has only one output head.

**Comment by hukim93** [comment]
I really appreciate your comments.
All things are now clear, thank you!
