### ISSUE TITLE
关于检测头的二值化

### ISSUE THREAD

**Issue by yuhua666** [ZiweiWangTHU/BiDet#50]
您好，关于检测头的二值化，我有以下疑问希望能够请教：
1.在RPN_head中，我注意到您除了将第一层卷积二值化了，还修改了proposal_layer的方式，代码如下：
```
# define proposal layer
        self.RPN_proposal = _ProposalLayer_IB(self.feat_stride, self.anchor_scales,
                                              self.anchor_ratios, self.sample_sigma)
```
想请问一下这里的修改的作用是什么吗，它对应的是论文里提及的IB准则吗？
2.关于检测头的二值化，按照我对代码的理解，RPN_Head和Roi_Head中，仅有RPN_Head的第一层被二值化了，这样的理解对吗？
非常感谢！

**Comment by Wuziyi616** [comment]
1. 因为 RPN 里也涉及到 bbox prediction, 所以也加上了 IB loss
2. 你的理解是对的，你也可以看代码里的部分来验证

**Comment by yuhua666** [comment]
非常感谢解答，我想再问一下，这个IB loss有什么用呢？是用于适应于二值化网络，提升其性能的吗？这个IB loss具体来说是影响哪哪些部分？很希望能够向您进一步学习。

**Comment by Wuziyi616** [comment]
用于提升性能 大概1-2个点
具体原因分析 原理请看论文

**Comment by yuhua666** [comment]
感谢！！！

**Comment by yuhua666** [comment]
抱歉，我还有问题，我希望能够将IB准则迁移到我自己的代码中，请问我需要修改哪些地方呢？

**Comment by Wuziyi616** [comment]
因个人时间有限 无法对 custom model 进行支持 请谅解
请 close issue
