### ISSUE TITLE
关于检测头二值化问题的请教

### ISSUE THREAD

**Issue by yuhua666** [ZiweiWangTHU/BiDet#51]
博士您好！
关于fasterrcnn的bbox_head，我尝试在自己的代码上进行了二值化，却导致了精度为零，我还原了这一部分为全精度，确认是二值化导致的。我想请问，在您的代码里面，bbox的最后两层shared_fcs层您进行二值化了吗？具体来说，是以下结构：
`(shared_fcs): ModuleList(
        13.896 M, 29.052% Params, 13.894 GFLOPs, 54.616% FLOPs,
        (0): Linear(12.846 M, 26.857% Params, 12.845 GFLOPs, 50.494% FLOPs, in_features=12544, out_features=1024, bias=True)
        (1): Linear(1.05 M, 2.194% Params, 1.049 GFLOPs, 4.122% FLOPs, in_features=1024, out_features=1024, bias=True)
      )`

**Comment by Wuziyi616** [comment]
我没有在 fasterrcnn 的代码里找到叫 `shared_fcs` 的层，你可以把那一行 link 给我吗？按我的记忆，最后的几层 output layer 应该是没有二值化的

**Comment by yuhua666** [comment]
具体来说，我使用的是mmdetection
在roi_head的后面，有一个bbox_head，mmdetection里使用了convfc_bbox_head。
具体代码如下：
`if num_branch_fcs > 0:
            # for shared branch, only consider self.with_avg_pool
            # for separated branches, also consider self.num_shared_fcs
            if (is_shared
                    or self.num_shared_fcs == 0) and not self.with_avg_pool:
                last_layer_dim *= self.roi_feat_area
            for i in range(num_branch_fcs):
                fc_in_channels = (
                    last_layer_dim if i == 0 else self.fc_out_channels)
                branch_fcs.append(
                    nn.Linear(fc_in_channels, self.fc_out_channels))
            last_layer_dim = self.fc_out_channels
        return branch_convs, branch_fcs, last_layer_dim`
这里包含了两个Linear层，其中一个占了12.846M参数。
但当我将其binary后，mAP显示为0，这给我带来了迷惑。
您能帮助我吗，感激不尽！

**Comment by Wuziyi616** [comment]
嗯嗯 那就是没有二值化

**Comment by yuhua666** [comment]
论文中报告的faster rcnn模型只有两兆多，而这个全连接层占了12.846M，这里给我带来了迷惑。

**Comment by yuhua666** [comment]
我输出了您代码中的网络结构，具体来说对应的是这两个全连接层：
(RCNN_cls_score): Linear(in_features=512, out_features=81, bias=True)
(RCNN_bbox_pred): Linear(in_features=512, out_features=8, bias=True)
想请教下您是修改了fasterrcnn原有的这两层结构使其参数量减少了吗？期待您的指导。

**Comment by Wuziyi616** [comment]
大概是因为我把最后的 feature map 取了 GlobalAvgPooling ([C, H, W] --> [C]), 而不是默认的 flatten ([C, H, W] --> [C\*H\*W]), 因此 Linear layer in_features 减少了很多, 所以 Linear layer 的参数量减少了很多；具体记不太清了，需要你自己去看代码

**Comment by yuhua666** [comment]
很抱歉，我还有疑问，希望能够赐教。
我在自己的网络上更换更小参数的检测头，或使用您提及的GAP方式减少参数量，但导致了mAP的大幅度下降。在实值网络上选择更弱的检测头降低的并没有那么明显。
您先前遇到过这一问题吗？如果您能提供一些经验上的指导，或者一些推测，我将不胜感激。
