### ISSUE TITLE
关于faster rcnn的FPN

### ISSUE THREAD

**Issue by yuhua666** [ZiweiWangTHU/BiDet#52]
我注意到原始的faster rcnn代码中，包含了FPN层，它在backbone和rpnhead之间，但您的代码中我似乎没有找到这一结构。
您使用了一些策略来替代FPN吗，还是作了怎样的修改呢，很感谢您可以为我解答。

**Comment by Wuziyi616** [comment]
原始的 fasterrcnn 其实是没有用 FPN 的，毕竟 FPN 的文章比 FRCNN 晚发表 (这种问题不用向我确认 自己去看源码就行了)
所以我的实现中也没有使用 FPN
