### ISSUE TITLE
在其他数据集上训练

### ISSUE THREAD

**Issue by yuhua666** [ZiweiWangTHU/BiDet#54]
博士您好，我想使用BiDet在其他数据集上进行训练，数据集已整理成COCO格式，但在APs、APm、APl这几个指标上有不同，我的是另外四个规模的，想请教一下我应该如何修改代码？

**Comment by Wuziyi616** [comment]
抱歉 个人时间有限 没有办法做 custom dataset 上的支持
请 close issue
