### ISSUE TITLE
Question on pretrained models.

### ISSUE THREAD

**Issue by killawhale2** [ZiweiWangTHU/BiDet#9]
I've sent an email to the authors roughly 2 weeks ago about the pretrained models but haven't got a response yet (maybe the email didn't go?) so I'm re-iterating the question here.

For obtaining the pretrained weights of ResNet18/VGG16, do you train the networks as a floating point network or do you binarize the networks like in XNOR-Net/Bi-Real Net and then train them on ImageNet to obtain the pretrained weights?

I'm trying to use different backbone networks and an answer to this question would help me in obtaining the pretrained weights for my networks.

**Comment by Wuziyi616** [comment]
Hi! Yes, I didn't get the email you mentioned, maybe you sent it to the wrong person I guess. As for your question, yes we trained **binarized** backbone networks on ImageNet for our detector. For example, we follow Bi-Real Net's training strategy to train our Bi-Real-VGG/ResNet (first real-valued with relu activation, then clipping activation, finally binary activation & weights). The training takes a long time (about 2 days for one model), and I use a large batch size on 4 GPUs to stabilize the training of the binary backbones. Hope my answer can help you!

**Comment by killawhale2** [comment]
Thank you for your quick reply!
